#!/usr/bin/env python3
"""Lab 13 Challenge:  print() and input()
   Ask input (user's name) and day of week, then print both concatenated to std out."""

# The following function contains code to accomplish task
def main():

    # ask user's name and wait for user input
    user_name = input("Good Morning! My name is Ronny. What's your name? ")

    # display input
    print("Hi, " + user_name + "! Good to meet you!")
    
    # ask user what day it is; wait for user input
    what_day = input("Can you tell me what day of the week it is? ")

    # unused option to  display the two user inputs together
    # print("Great! Thanks, " + user_name + "! Have a great " + what_day + "!")

    # option I chose (f-print) to display both user inputs together
    print(f"Thanks so much, {user_name}! Have a great {what_day}!")
    

    
main()


